 
version: 2.1

orbs:
  node: 'circleci/node@4.0.0'
  codecov: 'codecov/codecov@1.0.2'

jobs:
  test:
    executor:
      name: node/default

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn jest --coverage
      - codecov/upload:
          file: ./coverage/coverage-final.json

workflows:
  test_my_app:
    jobs:
      - test