name: test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      
      - name: Run tests
        run: yarn test
      
      - name: Check linting
        run: yarn lint
      
      - name: Upload code coverage results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}